### ISSUE TITLE
Where can I get the dataset you are using in the paper?

### ISSUE THREAD

**Issue by htshts1115** [JuewenPeng/MPIB#1]
Hi, I see that you generate dataset by ray-tracing renderer, which is claimed to be better than the datasets mentioned in the paper. Could you upload this dataset for study usage? 
Thank you very much.

**Comment by JuewenPeng** [comment]
I'm sorry, but we don't plan to provide this dataset. Instead, I uploaded the code of bokeh generator just now. You can use it to synthesize your own dataset conditioned on some RGBA images as described in our paper.

**Comment by htshts1115** [comment]
That is very nice. Many thanks.
I see your consecutive work on nn-bokeh, impressive jobs, well done!
