### ISSUE TITLE
May be Incomplete Instructions

### ISSUE THREAD

**Issue by TouqeerAhmad** [JuewenPeng/MPIB#2]
Hello, 

I was trying the demo code following the command shared in Readme. I did see an error about missing best_resave_pjw.pth model from Lama. 

`FileNotFoundError: [Errno 2] No such file or directory: '/data4/pengjuewen/Code/lama/LaMa_models/lama-places/lama-fourier/models/best_resave_pjw.pth'`

As per README, inpnet.pth is the in-painting network from Lama, may be some instructions are missing to run the demo?

Thanks!

**Comment by TouqeerAhmad** [comment]
Probably comment line 52 https://github.com/JuewenPeng/MPIB/blob/5dd40d7ad02649402f1cba537cd24027d7909bb3/demo.py#L52 and uncomment subsequent line in demo.py?

**Comment by JuewenPeng** [comment]
Thank you for pointing out this mistake.
