### ISSUE TITLE
Which Model to use for Disparity 

### ISSUE THREAD

**Issue by TouqeerAhmad** [JuewenPeng/MPIB#3]
Hello, 
You've mentioned DPT for disparity estimation. It looks like they have four different variants. Can you please specify which specific depth model you have used. Here is the four possibilities as noted in DPT's repo.

- [dpt_hybrid-midas-501f0c75.pt](https://github.com/intel-isl/DPT/releases/download/1_0/dpt_hybrid-midas-501f0c75.pt)
- [dpt_large-midas-2f21e586.pt](https://github.com/intel-isl/DPT/releases/download/1_0/dpt_large-midas-2f21e586.pt)
- [dpt_hybrid_kitti-cb926ef4.pt](https://github.com/intel-isl/DPT/releases/download/1_0/dpt_hybrid_kitti-cb926ef4.pt)
- [dpt_hybrid_nyu-2ce69ec7.pt](https://github.com/intel-isl/DPT/releases/download/1_0/dpt_hybrid_nyu-2ce69ec7.pt)

Thanks!

**Comment by JuewenPeng** [comment]
Thank you for your attention. I used the first one you list in all of my experiments.
